### ISSUE TITLE
Shared Preferences versions conflict

### ISSUE THREAD

**Issue by frederic33** [BirjuVachhani/adaptive_theme#10]
I need to use the 2.0 version of Shared_Preferences for NullSafety reason and others fix. I have to use Adaptative_Theme because this is awesome and so clear ! But it seems I have a conflict with version requirements :

/Users/fred/Documents/Flutter/development/flutter/bin/flutter --no-color pub get
Running "flutter pub get" in weekpath...                        

Because adaptive_theme 1.1.0 depends on shared_preferences >=0.5.0 <1.0.0 and no versions of adaptive_theme match >1.1.0 <2.0.0, adaptive_theme ^1.1.0 requires shared_preferences >=0.5.0 <1.0.0.
So, because <myapp> depends on both adaptive_theme ^1.1.0 and shared_preferences ^2.0.4, version solving failed.
pub get failed (1; So, because <myapp> depends on both adaptive_theme ^1.1.0 and shared_preferences ^2.0.4, version solving failed.)

It is possible to update adaptative_theme or a way to change something as workaround ? 

Thank you, Fred

**Comment by BirjuVachhani** [comment]
Hey there. I have published a pre-release for nullsafety. You can use it for now. I'll be updating this to stable null safety version.

```yaml
dependencies:
  adaptive_theme: ^2.0.0-nullsafety.1
```

**Comment by BirjuVachhani** [comment]
@frederic33 I just released stable version for null safety. 

https://pub.dev/packages/adaptive_theme
