### ISSUE TITLE
getting current theme return null 

### ISSUE THREAD

**Issue by kephren226** [BirjuVachhani/adaptive_theme#12]
using AdaptiveTheme.getThemeMode() or AdaptiveTheme.of(context).mode.isLight and AdaptiveTheme.of(context).mode.isDark return null when theme in not persisted

**Comment by BirjuVachhani** [comment]
Could you please share some code and version of the library you’re using??

**Comment by kephren226** [comment]
Just updated to latest version 


lass MyApp extends StatelessWidget {
  final AdaptiveThemeMode savedThemeMode;
  const MyApp({Key key, this.savedThemeMode}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return AdaptiveTheme(
      light: ThemeData(
        brightness: Brightness.light,
        primarySwatch: Colors.blue,
        primaryColor: Colors.blue[600],
        accentColor: Colors.blue,
        fontFamily: 'OpenSans',
      ),
      dark: ThemeData(
        brightness: Brightness.dark,
        primarySwatch: Colors.blue,
        primaryColor: Colors.blue[600],
        accentColor: Colors.blue,
        fontFamily: 'OpenSans',
      ),
      initial: savedThemeMode ?? AdaptiveThemeMode.light,
      builder: (theme, darkTheme) => ScreenUtilInit(
        designSize: const Size(750, 1334),
        allowFontScaling: false,
        builder: () => MaterialApp(
          title: 'D-COLLECT',
          routes: customRoutes,
          theme: theme,
          darkTheme: darkTheme,
          home: const Nav(),
        ),
      ),
    );
  }
}

**Comment by kephren226** [comment]
Just updated to last version 


`lass MyApp extends StatelessWidget {
  final AdaptiveThemeMode savedThemeMode;
  const MyApp({Key key, this.savedThemeMode}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return AdaptiveTheme(
      light: ThemeData(
        brightness: Brightness.light,
        primarySwatch: Colors.blue,
        primaryColor: Colors.blue[600],
        accentColor: Colors.blue,
        fontFamily: 'OpenSans',
      ),
      dark: ThemeData(
        brightness: Brightness.dark,
        primarySwatch: Colors.blue,
        primaryColor: Colors.blue[600],
        accentColor: Colors.blue,
        fontFamily: 'OpenSans',
      ),
      initial: savedThemeMode ?? AdaptiveThemeMode.light,
      builder: (theme, darkTheme) => ScreenUtilInit(
        designSize: const Size(750, 1334),
        allowFontScaling: false,
        builder: () => MaterialApp(
          title: 'D-COLLECT',
          routes: customRoutes,
          theme: theme,
          darkTheme: darkTheme,
          home: const Nav(),
        ),
      ),
    );
  }
}
`

**Comment by kephren226** [comment]
just updated to last versuion



`lass MyApp extends StatelessWidget {
  final AdaptiveThemeMode savedThemeMode;
  const MyApp({Key key, this.savedThemeMode}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return AdaptiveTheme(
      light: ThemeData(
        brightness: Brightness.light,
        primarySwatch: Colors.blue,
        primaryColor: Colors.blue[600],
        accentColor: Colors.blue,
        fontFamily: 'OpenSans',
      ),
      dark: ThemeData(
        brightness: Brightness.dark,
        primarySwatch: Colors.blue,
        primaryColor: Colors.blue[600],
        accentColor: Colors.blue,
        fontFamily: 'OpenSans',
      ),
      initial: savedThemeMode ?? AdaptiveThemeMode.light,
      builder: (theme, darkTheme) => ScreenUtilInit(
        designSize: const Size(750, 1334),
        allowFontScaling: false,
        builder: () => MaterialApp(
          title: 'D-COLLECT',
          routes: customRoutes,
          theme: theme,
          darkTheme: darkTheme,
          home: const Nav(),
        ),
      ),
    );
  }
}
`

**Comment by kephren226** [comment]
Just updated to last version 

lass MyApp extends StatelessWidget {
  final AdaptiveThemeMode savedThemeMode;
  const MyApp({Key key, this.savedThemeMode}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return AdaptiveTheme(
      light: ThemeData(
        brightness: Brightness.light,
        primarySwatch: Colors.blue,
        primaryColor: Colors.blue[600],
        accentColor: Colors.blue,
        fontFamily: 'OpenSans',
      ),
      dark: ThemeData(
        brightness: Brightness.dark,
        primarySwatch: Colors.blue,
        primaryColor: Colors.blue[600],
        accentColor: Colors.blue,
        fontFamily: 'OpenSans',
      ),
      initial: savedThemeMode ?? AdaptiveThemeMode.light,
      builder: (theme, darkTheme) => ScreenUtilInit(
        designSize: const Size(750, 1334),
        allowFontScaling: false,
        builder: () => MaterialApp(
          title: 'D-COLLECT',
          routes: customRoutes,
          theme: theme,
          darkTheme: darkTheme,
          home: const Nav(),
        ),
      ),
    );
  }
}

**Comment by BirjuVachhani** [comment]
This is just the configuration of AdaptiveTheme. Could you please also add code where you're facing problem?

**Comment by kephren226** [comment]
> Could you please share some code and version of the library you’re using??

  adaptive_theme: ^2.0.0

**Comment by BirjuVachhani** [comment]
This seems to be fine. Where you're getting the error? Are you getting stacktrace?

**Comment by kephren226** [comment]
Everywhere i use print(AdaptiveTheme.of(context).mode.isLight) and  print(AdaptiveTheme.of(context).mode.isLight) i get false for the 2

and await AdaptiveTheme.getThemeMode() return null

**Comment by kephren226** [comment]
Here for instance 

Widget build(BuildContext context) {
    print(AdaptiveTheme.of(context).mode.isLight);
......

**Comment by kephren226** [comment]
It works fine now

**Comment by gadgetreviews** [comment]
I am facing same problem: ~~~await AdaptiveTheme.getThemeMode()~~~ always returns null. What am I missing?

~~~
void init() async {
  WidgetsFlutterBinding.ensureInitialized();
  final savedThemeMode = await AdaptiveTheme.getThemeMode();
  print("DEBUG: savedThemeMode: "+savedThemeMode.toString());
  runApp(MyApp());
}
~~~

**Comment by kephren226** [comment]
Can you passe the mode to MyApp and try printing there to see what happens

**Comment by gadgetreviews** [comment]
same. null again.
~~~
... 
# at pubspec.yaml
  adaptive_theme: ^2.2.0
...
import 'package:adaptive_theme/adaptive_theme.dart';
import 'package:flutter/material.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  final savedThemeMode = await AdaptiveTheme.getThemeMode();
  print("DEBUG1: savedThemeMode: "+savedThemeMode.toString());
  runApp(MyApp(savedThemeMode: savedThemeMode));
}

class MyApp extends StatelessWidget {
  final AdaptiveThemeMode? savedThemeMode;

  MyApp({Key? key, @required this.savedThemeMode});

  @override
  Widget build(BuildContext context) {
    print("DEBUG2: savedThemeMode: "+savedThemeMode.toString());
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: ''),
    );
  }
}
~~~

**Comment by kephren226** [comment]
> same. null again.
> 
> ```
> ... 
> # at pubspec.yaml
>   adaptive_theme: ^2.2.0
> ...
> import 'package:adaptive_theme/adaptive_theme.dart';
> import 'package:flutter/material.dart';
> 
> void main() async {
>   WidgetsFlutterBinding.ensureInitialized();
>   final savedThemeMode = await AdaptiveTheme.getThemeMode();
>   print("DEBUG1: savedThemeMode: "+savedThemeMode.toString());
>   runApp(MyApp(savedThemeMode: savedThemeMode));
> }
> 
> class MyApp extends StatelessWidget {
>   final AdaptiveThemeMode? savedThemeMode;
> 
>   MyApp({Key? key, @required this.savedThemeMode});
> 
>   @override
>   Widget build(BuildContext context) {
>     print("DEBUG2: savedThemeMode: "+savedThemeMode.toString());
>     return MaterialApp(
>       debugShowCheckedModeBanner: false,
>       theme: ThemeData(
>         primarySwatch: Colors.blue,
>       ),
>       home: MyHomePage(title: ''),
>     );
>   }
> }
> ```

I think you should do something like this   initial: savedThemeMode ?? AdaptiveThemeMode.light  before printing
It seems like you did not persist any mode and use AdaptiveTheme.of(context).setLight() or this AdaptiveTheme.of(context).setDark()  to persist the selected theme

**Comment by kephren226** [comment]
My build method looks lik this 

 Widget build(BuildContext context) {
    return AdaptiveTheme(
      light: ThemeData(
        brightness: Brightness.light,
        primarySwatch: Colors.blue,
        primaryColor: Colors.blue[600],
        accentColor: Colors.blue,
        fontFamily: 'OpenSans',
      ),
      dark: ThemeData(
        brightness: Brightness.dark,
        primarySwatch: Colors.blue,
        accentColor: Colors.blue,
        fontFamily: 'OpenSans',
      ),
      initial: savedThemeMode ?? AdaptiveThemeMode.light,
...

**Comment by gadgetreviews** [comment]
> savedThemeMode ?? AdaptiveThemeMode.light

In android 10 emulator I choose Dark theme. then I run the app, and I get null. If I run the code above I will always get light theme even I choose dark theme. 
In fact I just need to get current theme. I don't need the rest of this plugin. Is there any other way or other plugin to get current theme?

**Comment by kephren226** [comment]
Youl will always get the light theme if you don't persist the selected one 
And the plugin need shared_preferences to persist the theme

**Comment by gadgetreviews** [comment]
But I need the system's theme setting, not plugin's.

**Comment by kephren226** [comment]
> But I need the system's theme setting, not plugin's.

I don't understand what you're trying to do

**Comment by gadgetreviews** [comment]
I have my own theme system. I just don't have a method to get current theme of android system. When my app opens it should look at android system theme. if it is dark, I will choose dark theme of my app as default. if it is light, I will choose light theme of my app as default. So I need to know current theme of android system. But I can't find any way to get that information.

**Comment by kephren226** [comment]
> I have my own theme system. I just don't have a method to get current theme of android system. When my app opens it should look at android system theme. if it is dark, I will choose dark theme of my app as default. if it is light, I will choose light theme of my app as default. So I need to know current theme of android system. But I can't find any way to get that information.

You cannot get the current theme of the phone if you did not persist anything 
Here is how you persist the system the theme AdaptiveTheme.of(context).setSystem()

that tell the app to get the system theme when starting 
your code did not persist anything

**Comment by gadgetreviews** [comment]
When I call 
~~~
    AdaptiveTheme.of(context).setSystem();
~~~
I get following error:
~~~
[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
~~~

**Comment by BirjuVachhani** [comment]
@gadgetreviews What you want is not what this package does. YOU DON'T NEED THIS PACKAGE!

This is what you want: https://stackoverflow.com/a/56307575/9199362

**Comment by gadgetreviews** [comment]
> @gadgetreviews What you want is not what this package does. YOU DON'T NEED THIS PACKAGE!
> 
> This is what you want: https://stackoverflow.com/a/56307575/9199362

Thanks. It worked and it is what I was looking for.
