### ISSUE TITLE
[Question] How to get 'Get ThemeMode At App Start', working?

### ISSUE THREAD

**Issue by joe733** [BirjuVachhani/adaptive_theme#13]
Following [Get ThemeMode at App Start](https://github.com/BirjuVachhani/adaptive_theme#get-thememode-at-app-start), my code looks like this:

```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  final savedThemeMode = await AdaptiveTheme.getThemeMode();
  runApp(MyApp(savedThemeMode: savedThemeMode)); // error here!
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return AdaptiveTheme(
      light:
          ThemeData(brightness: Brightness.light, primarySwatch: Colors.pink),
      dark:
          ThemeData(brightness: Brightness.dark, primarySwatch: Colors.teal),
      initial: savedThemeMode ?? AdaptiveThemeMode.light,
      builder: (theme, darktheme) => MaterialApp(
        title: 'Schedule',
        theme: theme,
        darkTheme: darktheme,
        home: MyHomePage(
          title: 'Schdeule',
        ),
      )
    );
  }
}
```

But I get an error saying:

```
The named parameter 'savedThemeMode' isn't defined.
Try correcting the name to an existing named parameter's name, or defining a named parameter with the name 'savedThemeMode'.dart(undefined_named_parameter)
```

Please pardon my ignorance in Dart and/or Flutter and show me how to resolve this.

**Comment by BirjuVachhani** [comment]
@joe733 This does not have to do anything with the library. You're missing declaration for `savedThemeMode` in your `MyApp` class.

This should fix it:

```dart
class MyApp extends StatelessWidget {
  final AdaptiveThemeMode savedThemeMode;
  
  MyApp({Key key,@required this.savedThemeMode});

  ...
}
```

**Comment by joe733** [comment]
Thanks a lot... still learning :)

Had to change `widget_test.dart` to 

```dart
import 'package:adaptive_theme/adaptive_theme.dart';
...

void main() {
  AdaptiveThemeMode savedThemeMode;
  testWidgets('Counter increments smoke test', (WidgetTester tester) async {
    // Build our app and trigger a frame.
    await tester.pumpWidget(MyApp(
      savedThemeMode: savedThemeMode,
    ));
...
```

**Comment by BirjuVachhani** [comment]
@joe733 You're welcome. Happy to help. 😊

**Comment by agarnet74** [comment]
Hi, 
I have the same issue but I don't understand neither your answer or his change : 

import 'package:flutter/material.dart';
import 'package:adaptive_theme/adaptive_theme.dart';
import 'pages/home_page.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  final savedThemeMode = await AdaptiveTheme.getThemeMode();
  runApp(MyApp(savedThemeMode : savedThemeMode));
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return AdaptiveTheme(
        light: ThemeData(
          brightness: Brightness.light,
          primarySwatch: Colors.lightBlue,
          accentColor: Colors.purple,
        ),
        dark: ThemeData(
          brightness: Brightness.dark,
          primarySwatch: Colors.lightBlue,
          accentColor: Colors.purple,
        ),
        initial: savedThemeMode ?? AdaptiveThemeMode.light,
        builder: (theme, darkTheme) => MaterialApp(
              debugShowCheckedModeBanner: false,
              title: 'Namka Nav',
              theme: theme,
              darkTheme: darkTheme,
              home: HomePage(),
            ));
  }
}

issue : The named parameter 'savedThemeMode' isn't defined.
Try correcting the name to an existing named parameter's name, or defining a named parameter with the name 'savedThemeMode'.

What am I missing ?

Thanks

**Comment by agarnet74** [comment]
`import 'package:flutter/material.dart';
import 'package:adaptive_theme/adaptive_theme.dart';
import 'pages/home_page.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  final _savedThemeMode = await AdaptiveTheme.getThemeMode();
  runApp(MyApp(savedThemeMode : _savedThemeMode));
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return AdaptiveTheme(
        light: ThemeData(
          brightness: Brightness.light,
          primarySwatch: Colors.lightBlue,
          accentColor: Colors.purple,
        ),
        dark: ThemeData(
          brightness: Brightness.dark,
          primarySwatch: Colors.lightBlue,
          accentColor: Colors.purple,
        ),
        initial: savedThemeMode ?? AdaptiveThemeMode.light,
        builder: (theme, darkTheme) => MaterialApp(
              debugShowCheckedModeBanner: false,
              title: 'Namka Nav',
              theme: theme,
              darkTheme: darkTheme,
              home: HomePage(),
            ));
  }
}
`

**Comment by BirjuVachhani** [comment]
@agarnet74 
Compare your code with the [example app](https://github.com/BirjuVachhani/adaptive_theme/blob/main/example/lib/main.dart) and you will see what you're missing!

Your `MyApp` should have this: 
```dart
class MyApp extends StatelessWidget {

final AdaptiveThemeMode? savedThemeMode;

const MyApp({Key? key, this.savedThemeMode}) : super(key: key);

}
```

**Comment by agarnet74** [comment]
Thanks, it works fine !
