### ISSUE TITLE
get theme and get darkTheme returns the same theme dependend on mode

### ISSUE THREAD

**Issue by bernhardfrenking** [BirjuVachhani/adaptive_theme#16]
Retrieving the ThemeData with get theme and get darkTheme will return not the expected themes of light theme and dark theme, instead both return the "active" theme.

**To Reproduce**
Compare `AdaptiveTheme.of(context).theme ` with `AdaptiveTheme.of(context).darkTheme;`.

**Expected behavior**
theme returns the light theme and darkTheme returns the dark theme.

**Responsible Code** 
from adaptive_theme.dart, which is cousing this behaviour:
```
  @override
  ThemeData get theme => preferences.mode.isDark ? _darkTheme : _theme;

  @override
  ThemeData get darkTheme => preferences.mode.isLight ? _theme : _darkTheme;
```

**Comment by BirjuVachhani** [comment]
Available in [2.1.0](https://github.com/BirjuVachhani/adaptive_theme/releases/tag/2.1.0)
