### ISSUE TITLE
System mode does not work on macOS

### ISSUE THREAD

**Issue by friebetill** [BirjuVachhani/adaptive_theme#19]
**Describe the bug**
When I launch my app on macOS and set the mode to system, the theme is not matched to the macOS system theme. The system theme works fine on Android and iOS.

**Comment by BirjuVachhani** [comment]
@friebetill This has been recently fixed. Which version are you using?

**Comment by friebetill** [comment]
I am using the latest version `2.2.0`. Restarting the app with the macOS dark theme active, doesn't solve the problem either.

**Comment by BirjuVachhani** [comment]
@friebetill Interesting!

1. Please share example code to reproduce this.
2. Please share steps to reproduce

**Comment by friebetill** [comment]
I have found the error in my code 🙈
Thank you for your attention!
