### ISSUE TITLE
Add custom mode

### ISSUE THREAD

**Issue by kephren226** [BirjuVachhani/adaptive_theme#21]
hello
Is there a way to add a third mode ?

For instance i want a dark blue background as a third option 
I can i do that if possible 

If not it will be very cool to have such an option

**Comment by BirjuVachhani** [comment]
Flutter only has 3 modes for theming so does this package. Which means you need to utilize existing mode for any customization you want. 

Checkout [Changing Themes](https://github.com/BirjuVachhani/adaptive_theme#changing-themes) section. You can set your `blue background` theme by replacing dark theme. (even if I give you option to provide custom themes. This is what I have to do internally!)

**Comment by kephren226** [comment]
I saw that I the doc
What time I'm really asking is apart from the the 2 themes dark and light can I add on other one
I don't want to replace the black background with a blue one 
I want a black one and a blue one like in the twitter app

**Comment by BirjuVachhani** [comment]
Yes, it can be done as I said. Only a single theme is active at a time right? Twitter replaces the dark theme based on what mode is selected. and only 1 mode is active at a time. so replacing existing dark won't affect anything. I think you can manage that.

**Comment by kephren226** [comment]
Ok 
Think we still don't understand each other 
Thanks for taking time to reply 👍🏿
