### ISSUE TITLE
[AdaptiveTheme] builder parameters

### ISSUE THREAD

**Issue by IvoBiaus** [BirjuVachhani/adaptive_theme#25]
**Describe the bug**
The builder functions gives 2 parameters, both are Themes. According to the documentation and the examples like:
```builder: (theme, darkTheme) => MaterialApp(...``` the first one is always Light Theme and the second one is always Dark Theme. But its currently not working that way, both parameters are sending the same twice. When the app is on Light mode both params are Light Theme, and when the app is in dark mode, both params are Dark Theme.

**To Reproduce**
1. Create an AdaptiveTheme with dark and light themes
2. At the AdaptiveTheme's "builder" function call a print with both theme params and check they are the same at both app modes.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/43274372/130986483-8993248c-4db4-474a-9f23-97dbb02a590a.png)
![image](https://user-images.githubusercontent.com/43274372/130986849-db7e4a5d-e5b5-47fc-a66e-560e77b1059e.png)

**Desktop (please complete the following information):**
Doesnt matter

**Smartphone (please complete the following information):**
Doesnt matter

**Additional context**

**Comment by BirjuVachhani** [comment]
@IvoBiaus Both params will be different if theme mode is `system`.
