### ISSUE TITLE
syatem navigation bar color

### ISSUE THREAD

**Issue by kephren226** [BirjuVachhani/adaptive_theme#29]
Hello
is there a way to set system navigation bar color depending on theme ?

**Comment by BirjuVachhani** [comment]
You can listen to theme mode changes and set your status bar accordingly. I believe there's a package to manage that.

Check this out in [README.md](https://github.com/BirjuVachhani/adaptive_theme#listen-to-the-theme-mode-changes)

```dart
AdaptiveTheme.of(context).modeChangeNotifier.addListener(() {
  // set status bar here.
});
```

**Comment by kephren226** [comment]
Thanks 
I’ll close the issue for now
I’ll try the solution later to see what happen
