### ISSUE TITLE
addListener() - Null check operator used on a null value

### ISSUE THREAD

**Issue by Arfmann21** [BirjuVachhani/adaptive_theme#33]
As title, using
```
 AdaptiveTheme.of(context).modeChangeNotifier.addListener(() {
        // set status bar here.
        });
```

gives the error "Null check operator used on a null value".

I've tried putting in inside initState and AdaptiveTheme builder, none of it worked.

In documentation, there aren't any info on where to put this method.

**Comment by BirjuVachhani** [comment]
@Arfmann21 Can you please share the stacktrace and the code where you put this listener?

**Comment by BirjuVachhani** [comment]
@Arfmann21 The reason it is not mentioned in the docs where to put it, is that it depends on the usecase. What's your usecase?

FYI: You should not put it anywhere before `MaterialApp` widget. Certainly not in the AdaptiveTheme builder.
