### ISSUE TITLE
Flutter 3.0 build error

### ISSUE THREAD

**Issue by veselv2010** [BirjuVachhani/adaptive_theme#35]
**Describe the bug**
Can't build the project with Flutter 3.0

**To Reproduce**
1. Upgrade to Flutter 3.0
2. Build the application

**Expected behavior**
Working app

**Screenshots**
![image](https://user-images.githubusercontent.com/32619716/168068090-3911b00c-ae02-4df6-a702-e90ba0f022d4.png)

**Smartphone (please complete the following information):**
 - OS: Android 7.1.2

**Additional context**
i am using version `2.3.1`

**Comment by ThraaxSession** [comment]
@BirjuVachhani I think you forgot to update pub.dev, could it be?

**Comment by BirjuVachhani** [comment]
This has been fixed and released in [v3.0.0](https://pub.dev/packages/adaptive_theme/versions/3.0.0)
