### ISSUE TITLE
In flutter 3.10 AdaptiveThemeMode.system won't work as it should be.

### ISSUE THREAD

**Issue by YonasAlem** [BirjuVachhani/adaptive_theme#46]
**Describe the bug**
When the theme mode is AdaptiveThemeMode.system and the current phone's system theme is dark mode and when you launch the app it will display the dark theme. but while the app is opened and when you change the the phone's system theme to light mode the app will not reflect to the change. but after restart it will change to light mode. 

but vice versa is still working fines, when you launch the app from light mode.

before flutter 3.10 it works as it should.

**To Reproduce**
1. make sure AdaptiveThemeMode.system is applied.
2. if the app is opened close it.
3. change the system theme to dark mode
4. launch the app
5. we will see the dark mode applied to the app
6. change the systems theme to light mode while the app is opened.
7. the UI won't change to light.
8. but if I restart the app, the light mode will be applied.

**Expected behavior**
when changing the systems theme from dark to light, the app should also react to that.

**Screenshots**
No need.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Samsung galaxy a12 - real device

**Additional context**

**Comment by BirjuVachhani** [comment]
Thank you @YonasAlem for reporting this issue. Would you also provide some additional info like what device and OS were you able to reproduce this on? was it a simulator or a real device?

**Comment by YonasAlem** [comment]
Real android device.

**Comment by YonasAlem** [comment]
@BirjuVachhani I'm sorry for the delay. I found out that the problem was not in your packages, instead it was another package called #flutter_screenutil. and they fixed it. and its all working. sorry for misleading info on your packages.

**Comment by BirjuVachhani** [comment]
@YonasAlem No problem! Glad I could help!
