### ISSUE TITLE
Toggle between dark and light theme only

### ISSUE THREAD

**Issue by giga10** [BirjuVachhani/adaptive_theme#48]
Long time ago there was an issue regarding this - https://github.com/BirjuVachhani/adaptive_theme/issues/14, so this is kinda a resurrection of that. 😄

You already mentioned a solution there. I looked up the code, and it should be fairly simple to implement this with one optional parameter "useSystem" to toggleThemeMode method. I wanted to sumbit a PR, but found myself in dilemma what is the cleanest way to write this down, so I decided to ask you if you could do it. 😀

Btw, thank you for this package. It's awesome! 👌

**Comment by BirjuVachhani** [comment]
This is now available in `v3.4.0`

```dart
toggleThemeMode(useSystem: false);
```
