### ISSUE TITLE
Set system theme not functioning

### ISSUE THREAD

**Issue by Othniel16** [BirjuVachhani/adaptive_theme#5]
**Describe the bug**
I have three simple buttons to toggle between the various theme modes. But it seems only setLight and setDark methods work. setSystem method instead of setting to the device theme sets the theme to light even when the device is in dark mode.

**To Reproduce**
Code to reproduce the behavior:

Container(
          child: Column(
            children: [
              // light theme
              FlatButton(
                  onPressed: () {
                    AdaptiveTheme.of(context).setLight();
                  },
                  child: Text('Set  light')),

              // dark theme
              FlatButton(
                  onPressed: () {
                    AdaptiveTheme.of(context).setDark();
                  },
                  child: Text('Set  dark')),

              // system theme
              FlatButton(
                  onPressed: () {
                    AdaptiveTheme.of(context).setSystem();
                  },
                  child: Text('Set  system')),
            ],
          ),
)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome

**Smartphone (please complete the following information):**
 - Device: Samsung A10s (actual device) and a Google Pixel emulator
 - OS: Android 10
 - Browser: no browser

**Additional context**

**Comment by BirjuVachhani** [comment]
@Othniel16 I see you closed this. It is resolved or should I look into it?

**Comment by Othniel16** [comment]
> @Othniel16 I see you closed this. It is resolved or should I look into it?

Yes please it is resolved. Thanks for the reply
