### ISSUE TITLE
Make it possible to track only billable hours

### ISSUE THREAD

**Issue by JuliaMathias** [BirjuVachhani/adaptive_theme#53]
**Is your feature request related to a problem? Please describe.**
I use toggl to track both work-related things and personal development "tasks" that I set for myself. However the billable hours are the "important" ones for me, so it would be great if I could exclude non-billable hours when figuring out if I've achieved my target or not. 

**Describe the solution you'd like**
It would be great to have a setting that says something like "Exclude non-billable hours"

**Comment by BirjuVachhani** [comment]
Hi @JuliaMathias. Seems like you have posted this issue in wrong repository. Please file this on [TargetMate](https://github.com/BirjuVachhani/target_mate) repository. Thanks!
