### ISSUE TITLE
Get current theme?

### ISSUE THREAD

**Issue by sukhcha-in** [BirjuVachhani/adaptive_theme#6]
Is there any way to determine current theme and showing different icon for iconbutton?
`lightbulb` for light theme and `lightbulb_outline` for dark theme?
```
IconButton(
    icon: Icon(Icons.lightbulb_outline),
    onPressed: () {
        AdaptiveTheme.of(context).toggleThemeMode();
    },
)
```

**Comment by BirjuVachhani** [comment]
@sukhcha-in 
You can get  current theme mode (light | dark) like this:

```dart
AdaptiveTheme.of(context).mode.isLight

AdaptiveTheme.of(context).mode.isDark
```
