### ISSUE TITLE
on start the app theme doesn't apply quickly

### ISSUE THREAD

**Issue by mrcse** [BirjuVachhani/adaptive_theme#8]
there is the required files as requested

[lib.zip](https://github.com/BirjuVachhani/adaptive_theme/files/5560238/lib.zip)

[pubspec.zip](https://github.com/BirjuVachhani/adaptive_theme/files/5560243/pubspec.zip)

**Comment by BirjuVachhani** [comment]
@mrcse Please check this out: https://github.com/BirjuVachhani/adaptive_theme#get-thememode-at-app-start

**Comment by mrcse** [comment]
Ah now it is working thanks man........keep it up :)
