### ISSUE TITLE
Font not working correctly 

### ISSUE THREAD

**Issue by killerm250m** [BirjuVachhani/adaptive_theme#9]
Thank you for the library..

I noticed when I set the default font its not applied for the whole application

This is my code

AdaptiveTheme(
              light: ThemeData(
                primaryColor: MaterialWhite,
                accentColor: orangeColorDark,
                inputDecorationTheme: const InputDecorationTheme(
                  labelStyle: TextStyle(color: Colors.grey),
                  hintStyle: TextStyle(color: Colors.grey),
                ),
                primaryTextTheme: TextTheme(
                  headline6: TextStyle(
                    color: Colors.black,
                  ),
                  bodyText2: TextStyle(
                    color: Colors.black,
                  ),
                  bodyText1: TextStyle(
                    color: Colors.black,
                  ),
                  headline1: TextStyle(
                    color: Colors.black,
                  ),
                  headline2: TextStyle(
                    color: Colors.black,
                  ),
                  headline3: TextStyle(
                    color: Colors.black,
                  ),
                  headline4: TextStyle(
                    color: Colors.black,
                  ),
                  headline5: TextStyle(
                    color: Colors.black,
                  ),
                  subtitle1: TextStyle(
                    color: Colors.black,
                  ),
                  subtitle2: TextStyle(
                    color: Colors.black,
                  ),
                ),
                fontFamily: checkLanguage() ? 'lato_regular' : 'sans_full',
                textTheme: Theme.of(context).textTheme.apply(
                      bodyColor: Colors.black,
                      displayColor: Colors.black,
                    ),
                scaffoldBackgroundColor: HexColor('#ffffff'),
                backgroundColor: HexColor('#ffffff'),
              ),
              dark: ThemeData(
                brightness: Brightness.dark,
                primarySwatch: Colors.red,
                accentColor: Colors.amber,
                appBarTheme: AppBarTheme(
                    backgroundColor: HexColor('#121212'),
                    centerTitle: true,
                    elevation: 0),
                scaffoldBackgroundColor: HexColor('#212121'),
                backgroundColor: HexColor('#212121'),
                primaryTextTheme: TextTheme(
                  headline6: TextStyle(
                    color: Colors.white,
                  ),
                  bodyText2: TextStyle(
                    color: Colors.white,
                  ),
                  bodyText1: TextStyle(
                    color: Colors.white,
                  ),
                  headline1: TextStyle(
                    color: Colors.white,
                  ),
                  headline2: TextStyle(
                    color: Colors.white,
                  ),
                  headline3: TextStyle(
                    color: Colors.white,
                  ),
                  headline4: TextStyle(
                    color: Colors.white,
                  ),
                  headline5: TextStyle(
                    color: Colors.white,
                  ),
                  subtitle1: TextStyle(
                    color: Colors.white,
                  ),
                  subtitle2: TextStyle(
                    color: Colors.white,
                  ),
                ),
                textTheme: Theme.of(context).textTheme.apply(
                      bodyColor: Colors.white,
                      displayColor: Colors.white,
                    ),
                fontFamily: checkLanguage() ? 'lato_regular' : 'sans_full',
              ),

**Smartphone (please complete the following information):**
 - Device: Simulator iPhone11
 - OS: iOS13.5

**Comment by BirjuVachhani** [comment]
@killerm250m  This is not related to this library. This seems to be related to flutter framework. Try posting this over StackOverflow.

Thanks.
